spring:
  h2:
    console:
      enabled: true     
      path: /h2
  application:
    name: inv-module
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true